layer5io/sistent

- package.json
- packages/svg/src/icons/Circle/OutlinedCircleIcon.tsx
> added build-all in release

- .github/workflows/labeler.yml
This PR adds a  Pull Request Labeler Workflow
> [CI] Pull Request Labeler Workflow

- .github/labeler.yml
This PR creates configuration for automatic assignment of labels.
> [CI] Pull Request Labeler Config

- packages/components/src/togglebutton.tsx
- packages/components/src/togglebuttongroup.tsx
> [components] `togglebutton` and `togglebuttongroup` component

- packages/components/src/accordion.tsx
- packages/components/src/accordionactions.tsx
- packages/components/src/accordiondetails.tsx
- packages/components/src/accordionsummary.tsx
- packages/components/src/avatargroup.tsx
- packages/components/src/backdrop.tsx
- packages/components/src/badge.tsx
- packages/components/src/checkbox.tsx
- packages/components/src/radiogroup.tsx
- packages/components/src/slide.tsx
This PR relates to this open https://github.com/layer5io/sistent/issues/56
> [components] add 10 `MUI` components

- packages/components/src/button.tsx
> fix: update Button to use MUI props

- packages/svg/package.json
This PR is a manual release of `svg` library from the culmination of the commits we have done since this project has opened.
The current workflow for release seems to only work in the root directory, not throughout the monorepo layout.
To avoid publishing the root workspace, which is not needed at this, this is a manual release from the `svg` library.
I will be opening a new issue to track doing a release through using Makefile to account for the different package location.
Here is the open issue: https://github.com/layer5io/sistent/issues/71
> [svg] manual release `v0.6.0`

- MAINTAINERS.md
Antonette Caldwell (@nebula-aac)  is actively involved in the development of "Sistent," a comprehensive design system of Layer5. Her contributions to this project demonstrate her commitment to enhancing user experiences and visual consistency within Layer5 projects.
Antonette's dedication and expertise make her an invaluable asset to the Sistent project and the broader design community.
> Nomination of Antonette Caldwell as a maintainer of sistent

- packages/components/package.json
- packages/components/src/custom/ErrorBoundary.tsx
- packages/components/src/custom/index.ts
-[x] Added A ErrorBoundary FC 
-[x] Added withErrorBoundary HOC 
-[x] Added a withSuppresedErrorBoundary Component that supresses the error and hides the crashed component 
> [Component] Added Components for error boundaries

- system/patterns/empty-states.md
> [Design] Patterns: Empty State

- .husky/commit-msg
- .husky/prepare-commit-msg
- commitlint.config.js
- package.json
- yarn.lock
This PR is related to open issue: https://github.com/layer5io/sistent/issues/107
> chore(workspace): setup commitlint and commitizen along with husky

- packages/components/src/base/MuiTable/data-table.tsx
- packages/components/src/base/MuiTable/index.tsx
>  add data-table component

- .github/workflows/release.yml
> [CI] Trigger publishing flow when release is made

- packages/components/src/custom/Helpers/CondtionalTooltip/index.ts
- packages/components/src/custom/Helpers/CondtionalTooltip/tooltip-for-desc.tsx
> ConditionalTooltip as helper component

- README.md
- packages/components/src/base/Popper/index.ts
- packages/components/src/base/Popper/popper.tsx
- packages/components/src/custom/Toolbar/custom-column.tsx
- packages/components/src/custom/Toolbar/custom-filter.tsx
- packages/components/src/custom/Toolbar/custom-search.tsx
- packages/components/src/custom/Toolbar/index.ts
- packages/components/src/custom/Toolbar/viewColumn.tsx
- packages/svg/src/icons/Close/closeIcon.tsx
- packages/svg/src/icons/Close/index.ts
- packages/svg/src/icons/Column/columnIcon.tsx
- packages/svg/src/icons/Column/index.tsx
- packages/svg/src/icons/Search/intex.ts
- packages/svg/src/icons/Search/seacrhIcon.tsx
This PR adds:
Custom  components for toolbar
Related Issue: #118 #86 #125 
I will be adding column component for tables
> [components]: Toolbar custom components

- CNAME
This PR fixes #101. Related to #22 and #23.
> [Website] Create CNAME for design.layer5.io

- .github/workflows/build-and-deploy-site.yml
- .github/workflows/build-and-preview-site.yml
- .github/workflows/preview-site.yml
> GitHub workflows for deployment preview

- site/src/components/Footer/Footer.style.js
- site/src/pages/components/index.js
- site/src/pages/patterns/index.js
- site/src/pages/visualise/index.js
> Fix empty file build failure

- .github/workflows/build-and-deploy-site.yml
Signed-off-by: leecalcote <leecalcote@users.noreply.github.com>
> [CI] [Site] chore: upgrade JamesIves/github-pages-deploy-action@v4.4.3

- .github/ISSUE_TEMPLATE/feature_request.md
The links to the Figma design file have been updated from the Layer5 link to the Sistent link
> Figma design file link update

- .github/ISSUE_TEMPLATE/documentation.md
> Remove unrelated info from `ISSUE_TEMPLATE` related to doc

- src/custom/Feedback/style.tsx
- src/theme/colors/colors.ts
> feat(btn): fix dynamic

- src/custom/Feedback/style.tsx
- src/icons/Feedback/FeedbackIcon.tsx
[Screencast from 2024-03-14 11-44-16.webm](https://github.com/layer5io/sistent/assets/59491379/7e846d3b-092e-4e28-94c9-20c17ac7b9a6)
> refactor(icon): fixed the icon used for feedback

- README.md
This PR fixes broken link in documentation
> Fix broken link to community guide

- src/schemas/importDesign/schema.tsx
The earlier link was not available and was a 404 page
> Fix docs link in import design schema

- .github/label-commenter-config.yml
- .github/workflows/label-commenter.yml
> [CI] Add issue labeler workflow

- Makefile
- package.json
- src/base/Button/Button.tsx
- src/custom/Modal/index.tsx
- src/custom/Stepper/index.tsx
- src/custom/index.tsx
- src/icons/Close/CloseIcon.tsx
- src/icons/Info/InfoCircle.tsx
- src/icons/Info/index.tsx
- src/theme/components/button.modifier.ts
- yarn.lock
> feat : Create Custom modal and Stepper

- src/custom/TransferModal/TransferList/TransferList.tsx
https://github.com/layer5io/sistent/assets/90546692/0d6385a4-e76a-459e-b902-03badf9bcdc9
> Fix scroll issue in transferlist due to unnecessary dependency

- src/theme/ThemeProvider.tsx
- src/theme/index.tsx
> fix: add theme without baseline

- src/theme/ThemeProvider.tsx
> fix: remove logs

- README.md
- src/theme/components/formlabel.modifier.ts
- src/theme/components/input.modifier.ts
- src/theme/components/outlinedinput.modifier.ts
- src/theme/components/textfield.modifier.ts
> Typography for Input fields

- src/custom/StyledChapter/StyledChapter.tsx
- src/custom/TOCChapter/TOCChapter.tsx
> feat(components): enchancement

- src/custom/LearningCard/LearningCard.tsx
- src/custom/SetupPrerequisite/SetupPrerequisite.tsx
- src/custom/SetupPrerequisite/style.tsx
> feat(components): enchancement in learning component

- src/custom/SetupPrerequisite/SetupPrerequisite.tsx
- src/custom/SetupPrerequisite/style.tsx
- src/custom/StyledChapter/StyledChapter.tsx
> feat(components): no underline

- src/schemas/grafanaCredential/schema.tsx
- src/schemas/grafanaCredential/uiSchema.tsx
- src/schemas/index.tsx
- src/schemas/kubernetesCredential/schema.tsx
- src/schemas/kubernetesCredential/uiSchema.tsx
- src/schemas/prometheusCredential/schema.tsx
- src/schemas/prometheusCredential/uiSchema.tsx
> Add new schemas

- package-lock.json
- package.json
- src/custom/CustomTooltip/customTooltip.tsx
- src/custom/Feedback/FeedbackButton.tsx
> Update Custom tooltips to use markdown link formatter

- package-lock.json
- package.json
- src/custom/CustomTooltip/customTooltip.tsx
- src/custom/Feedback/FeedbackButton.tsx
> Revert "Update Custom tooltips to use markdown link formatter"

- src/custom/TransferModal/TransferList/style.tsx
> feat(components): ui bug

- src/theme/components/button.modifier.ts
This PR fixes css issue with button
> add style at button

- src/theme/components/button.modifier.ts
- src/theme/typography.ts
> Fix style of button

- src/custom/Modal/index.tsx
1. This PR fixes the modals header and background colors.
2. Adds a check for` helperText` if its not defined then fix the style of the footer
> Enhancements and fixes in modals

- src/custom/Feedback/style.tsx
> feat(components): feedback default colour for both mode

- src/custom/Markdown/style.tsx
> Fix correct token usage for tooltip

- src/custom/Modal/index.tsx
This PR fixes 
- border radius of modal
- dimensions for infoicon
> Fix some modal styles

- src/theme/components/button.modifier.ts
This PR uses a slight lower font weight for buttons
> Use less `fontWeight` for button

- src/custom/CustomTooltip/customTooltip.tsx
This PR adds a prop for bgColor to CustomTooltip
> feat: add bgColor prop to custom tooltip

- src/custom/Stepper/index.tsx
- src/icons/Add/AddIcon.tsx
- src/theme/index.tsx
- src/theme/theme.ts
> feat: enhance stepper

- src/custom/Modal/index.tsx
- src/custom/index.tsx
This PR adds a primary actions component using the existing primary and secondary button which will used in our standard modal
> Add primary actions component

- src/custom/Markdown/style.tsx
> fix margin for some tags in markdown support

- src/theme/ThemeProvider.tsx
> fix: sistent themeprovider to enable branding theme

- src/custom/LearningCard/LearningCard.tsx
- src/custom/TOCChapter/style.tsx
> [LEARNING-PATH] TOC list fix 

- src/theme/ThemeProvider.tsx
- src/theme/theme.ts
This PR fixes # 
fixes lose of reactivity when changing custom theme
> fix: enhance merging custom theme with basePallete

- src/custom/Modal/index.tsx
This PR updates tooltip variant used in modal footer.
> [Chore] Update modal footer tooltip variant

- src/theme/theme.ts
> Formatting

- src/theme/theme.ts
> Revert "Formatting"

- src/theme/theme.ts
> fix:  copy before mutating the theme

- src/custom/Note/Note.tsx
- src/custom/Note/index.tsx
- src/custom/SetupPrerequisite/SetupPrerequisite.tsx
- src/custom/SetupPrerequisite/style.tsx
- src/custom/index.tsx
> feat: note component for Learning-path

- src/custom/CustomTooltip/customTooltip.tsx
> [chore] Update default tooltip variant

- src/custom/Modal/index.tsx
> Make only modal-body scrollable

- src/schemas/helpAndSupportModal/schema.tsx
- src/schemas/helpAndSupportModal/uiSchema.tsx
This PR updates the required field for schema which i missed to update in last pr.
> Update required fields in schema

- src/custom/CustomImage/CustomImage.tsx
- src/custom/CustomImage/index.tsx
- src/custom/Note/Note.tsx
- src/custom/index.tsx
> chore: added render markdown in note component

- src/custom/CustomTooltip/customTooltip.tsx
> [chore] Increase hide delay for custom tooltip

- src/schemas/createAndEditWorkspace/uiSchema.tsx
Changed the name of Workspace schema to correct one.
This PR fixes # 681
> [Fix] Corrected Schema name

- src/theme/components/checkbox.modifier.ts
> chore: added inverseBackground in checkbox

- src/custom/CustomTooltip/customTooltip.tsx
> Revert "[chore] Increase hide delay for custom tooltip"

- src/theme/components/checkbox.modifier.ts
> fix: inner border of checkbox svg

- src/custom/TOCChapter/style.tsx
> fix: brand colors for TOC

- src/custom/Helpers/ResponsiveColumns/responsive-coulmns.tsx/index.tsx
- src/custom/Helpers/ResponsiveColumns/responsive-coulmns.tsx/responsive-column.tsx
- src/custom/ResponsiveDataTable.tsx
- src/custom/index.tsx
> Add column visibility responsive handler and add default options in table

- src/custom/CustomTooltip/customTooltip.tsx
- src/custom/ResponsiveDataTable.tsx
> Revert "Add `customtooltip` as default for tables and fix around it"

- src/custom/Markdown/style.tsx
> Fix color for link element of markdown to adhere org based theme

- src/custom/ResponsiveDataTable.tsx
- src/custom/TooltipIcon.tsx
- src/custom/index.tsx
- src/icons/Ellipsis/Ellipsisicon.tsx
- src/icons/Ellipsis/index.tsx
- src/theme/components/iconbutton.modifier.ts
> Add ellispis action menu and fix cursor styles 

- src/custom/ResponsiveDataTable.tsx
> Add checkbox as default

- src/custom/SetupPrerequisite/style.tsx
> fix: hyperlink styling in prereq card

- src/custom/CustomImage/CustomImage.tsx
- src/custom/SetupPrerequisite/style.tsx
> chore: lighthouse effect to 100% max width

- src/custom/StyledChapter/StyledChapter.tsx
> chore: added styling for code block in Learning-path and chapter

- src/custom/StyledChapter/StyledChapter.tsx
> chore: using brand colors

- src/custom/StyledChapter/StyledChapter.tsx
> chore: using code token

- src/custom/TOCChapter/TOCChapter.tsx
> fix: lettering capitalization in TOC

- src/custom/StyledChapter/StyledChapter.tsx
> fix: inline code block in learning-path

- src/custom/CatalogCard/style.tsx
> fix background of catalog card

- src/custom/TransferModal/TransferList/TransferList.tsx
- src/icons/Meshery/MesheryIcon.tsx
- src/icons/Meshery/index.ts
> chore: addition of transferlist kind based org

- src/custom/ChapterCard/style.tsx
- src/custom/LearningCard/style.tsx
- src/custom/SetupPrerequisite/style.tsx
- src/custom/StyledChapter/StyledChapter.tsx
> fix: styling issue learning-path content

- src/custom/CatalogCard/CatalogCard.tsx
> Add onclick to catalog card

- src/custom/CustomTooltip/customTooltip.tsx
> Change bgcolor of tooltip

- src/custom/Prompt/index.tsx
- src/custom/Prompt/promt-component.tsx
- src/custom/Prompt/style.tsx
- src/custom/index.tsx
**This PR adds promp component to sistent.**
**This component is used for our confirmation modal which used for either delete, save or any other confirmation process.**
-> These varaiants are basically what type of confirmation we want to display : danger, success ,warning or info
>[!NOTE]
> This use our same sistent standard modal 
> [component] Add Prompt Component

- package-lock.json
- src/actors/eventBus.ts
- src/actors/index.ts
- src/custom/index.tsx
- src/custom/permissions.tsx
> Implement permissions flow 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This PR fixes the issue template which was having some false information
> enhance issue templates

- src/schemas/importDesign/schema.tsx
> Remove default type from import design schema

- src/custom/Modal/index.tsx
- src/custom/index.tsx
I am exporting this for use into custom walkthrough modal related [#2887](https://github.com/layer5labs/meshery-extensions/pull/2887)
> Export modal style header and modal close button

- src/icons/Menu/MenuIcon.tsx
- src/icons/Menu/index.ts
- src/icons/index.ts
> chore: Add hamburger icon

- src/custom/NavigationNavbar/index.tsx
- src/custom/NavigationNavbar/navigationNavbar.tsx
- src/custom/NavigationNavbar/style.tsx
- src/custom/index.tsx
>  Create navigation navbar that present in cloud 

- src/custom/CustomTooltip/customTooltip.tsx
> Added box shadow to Tooltip component

- src/custom/CustomCatalog/custom-card.tsx
- src/custom/CustomCatalog/style.tsx
> Add some of the styling in custom catalog card

- src/custom/StyledSearchBar/StyledSearchBar.tsx
- src/custom/StyledSearchBar/style.tsx
> Convert cloud catalog sort menu and search field to sistent

- src/custom/StyledSearchBar/style.tsx
> update border color of the styled search that in cloud

- src/base/Skeleton/Skeleton.tsx
- src/base/Skeleton/index.tsx
- src/base/index.tsx
> Add new skeleton component

- src/custom/Markdown/index.tsx
- src/custom/Markdown/style.tsx
- src/custom/index.tsx
> changes to support markdown for notifications

- src/custom/CatalogFilterSection/CatalogFilterSidebar.tsx
- src/custom/CatalogFilterSection/style.tsx
- src/custom/StyledSearchBar/style.tsx
> update styling of search and filter for make consistent with the cloud

- src/theme/palette.ts
> update secondary background token

- src/custom/Modal/index.tsx
- src/theme/colors/colors.ts
>  update the gradient for the modal header diff for the dark and light mode

- src/custom/CatalogDetail/LeftPanel.tsx
- src/custom/CatalogDetail/RelatedDesigns.tsx
- src/custom/CatalogDetail/RightPanel.tsx
- src/custom/CatalogDetail/UserInfo.tsx
- src/custom/CatalogDetail/style.tsx
- Add org name in related designs
- Add user avatar inside userinfo
> Enhance catalog details

- .github/workflows/bump-meshery-version.yml
- .github/workflows/release.yml
> ci: fix release bump

- src/custom/InputSearchField/InputSearchField.tsx
>  make filter icon custom

- src/custom/CatalogDetail/ActionButton.tsx
> fix theme for action buttons

- src/constants/constants.ts
- src/custom/CatalogDetail/ChallengesSection.tsx
- src/custom/CatalogDetail/LearningSection.tsx
- src/custom/CatalogDetail/UserInfo.tsx
- src/custom/CatalogDetail/helper.ts
> update links to point to cloud.layer5.io

- src/custom/CatalogDesignTable/columnConfig.tsx
- src/custom/ResponsiveDataTable.tsx
- src/custom/TooltipIcon.tsx
> Fix some issue in the catalog design table

- src/custom/ResponsiveDataTable.tsx
> feat: remove width property from dataTableTheme for cleaner styling

- .github/workflows/bump-meshery-version.yml
> chore: udpate title auto pr sistent

- src/custom/CustomCatalog/style.tsx
- src/custom/PerformersSection/PerformersSection.tsx
- src/custom/PerformersSection/PerformersToogleButton.tsx
- src/custom/PerformersSection/index.ts
- src/custom/PerformersSection/styles.tsx
- src/custom/ResponsiveDataTable.tsx
- src/custom/index.tsx
- src/icons/Tropy/TropyIcon.tsx
- src/icons/Tropy/index.ts
- src/icons/index.ts
> Convert cloud performance section into sistent component

- src/custom/CatalogDesignTable/CatalogDesignTable.tsx
- src/custom/TooltipIcon.tsx
> fix: catalog table date and pagination issue

- src/custom/CatalogDesignTable/AuthorCell.tsx
- src/custom/CatalogDesignTable/CatalogDesignTable.tsx
- src/custom/CatalogDesignTable/columnConfig.tsx
- src/custom/CatalogDesignTable/index.ts
> feat: add AuthorCell component and integrate it into CatalogDesignTable

- src/custom/CatalogDetail/ActionButton.tsx
- src/custom/CatalogDetail/LeftPanel.tsx
- src/custom/CatalogDetail/style.tsx
> fix positioning and add info action

- src/custom/PerformersSection/PerformersSection.tsx
> change the heder title and icon position

- src/custom/PerformersSection/PerformersSection.tsx
> fix: icon click issue 

- src/schemas/importDesign/schema.tsx
This PR updates design import schema, to facilitate file upload for helm chart
> [Chore]: Schemas updated

- src/custom/CatalogDetail/SocialSharePopper.tsx
- src/custom/CatalogDetail/style.tsx
> fix share button UI

- src/custom/CatalogDetail/ActionButton.tsx
> fix theme of action menu

- src/custom/UserSearchField/index.ts
- src/custom/UserSearchField/index.tsx
> fix search for users in catalog

- src/custom/CatalogDesignTable/CatalogDesignTable.tsx
- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/CatalogDetail/RelatedDesigns.tsx
- src/custom/CatalogDetail/SocialSharePopper.tsx
- src/custom/CatalogDetail/style.tsx
- src/custom/CustomTooltip/customTooltip.tsx
- src/custom/ResponsiveDataTable.tsx
- src/custom/SearchBar.tsx
- src/custom/StyledSearchBar/style.tsx
- src/custom/TeamTable/TeamTableConfiguration.tsx
- src/custom/UsersTable/UsersTable.tsx
- src/custom/VisibilityChipMenu/VisibilityChipMenu.tsx
- src/custom/Workspaces/DesignTable.tsx
- src/custom/Workspaces/EnvironmentTable.tsx
- src/custom/Workspaces/WorkspaceTeamsTable.tsx
> Fix catalog bug and ui theme color issue

- src/custom/ResponsiveDataTable.tsx
>  update mui table theme

- src/theme/components.ts
- src/theme/components/tab.modifier.ts
- src/theme/components/tabs.modifier.ts
> [theme]: tabs custom theme

- src/custom/SearchBar.tsx
> feat: wrap the search component with the div

- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/CatalogDesignTable/columnConfig.tsx
- src/custom/CatalogDetail/ActionButton.tsx
- src/custom/CatalogDetail/LeftPanel.tsx
- src/custom/CatalogDetail/helper.ts
- src/custom/CatalogDetail/types.ts
- src/custom/Workspaces/DesignTable.tsx
> make download patters, filters from the server side

- src/custom/SearchBar.tsx
> [ui]: fix alignment of search bar

- src/custom/ShareModal/ShareModal.tsx
This PR use of proper tokens where it was missing.
> fix share modal theme for text and icon

- src/custom/CatalogDetail/SocialSharePopper.tsx
> fix share icon color in dark mode

- src/utils/components.ts
> fix: any types

- src/theme/colors/colors.ts
- src/theme/colors/index.ts
- src/theme/components/tab.modifier.ts
- src/theme/components/tabs.modifier.ts
- src/theme/palette.ts
> fix theme changes in tabs

- src/custom/ResourceDetailFormatters/Formatter.tsx
- src/custom/ResourceDetailFormatters/styles.ts
- src/custom/ResourceDetailFormatters/types.ts
- src/custom/ResourceDetailFormatters/useResourceCleanData.ts
> pass the container resource in the useResourceCleanData function

- src/custom/CatalogDetail/ActionButton.tsx
> feat: make clone button as a primary action

- src/custom/ShareModal/ShareModal.tsx
- src/custom/UserSearchField/UserSearchField.tsx
> fix: share is not working issue

- src/theme/components/button.modifier.ts
> fix hover color of outlined button

- src/custom/CatalogDetail/style.tsx
> remove unnecessary height dimension for share button to make it consistent

- .github/workflows/bump-meshery-version.yml
> [CI]: add legacy command to install package in layer5 while bump

- src/custom/TransferModal/TransferList/TransferList.tsx
- src/custom/Workspaces/AssignmentModal.tsx
- src/custom/Workspaces/DesignTable.tsx
- src/custom/Workspaces/WorkspaceViewsTable.tsx
- src/custom/Workspaces/hooks/useDesignAssignment.tsx
- src/custom/Workspaces/hooks/useViewsAssignment.tsx
- src/custom/Workspaces/index.ts
- src/custom/Workspaces/types.ts
> Add support for views in transferList

- src/base/Pagination/Pagination.tsx
- src/base/Pagination/index.tsx
- src/theme/palette.ts
> add pagination item component to sistent

- src/theme/palette.ts
> feat: add card name color token for toolbar

- src/custom/Workspaces/DesignTable.tsx
- src/custom/Workspaces/WorkspaceTeamsTable.tsx
- src/custom/Workspaces/hooks/useDesignAssignment.tsx
> fix: workspace teams table undefined issue

- package.json
- src/schemas/importDesign/schema.tsx
- src/schemas/importDesign/uiSchema.tsx
> Remove DesignType from import schema

- src/custom/ResponsiveDataTable.tsx
Make it compatible with the muiv5
> update mui data table theme

- src/theme/components/appbar.modifiter.ts
- src/theme/components/buttongroup.modifier.ts
- src/theme/components/link.modifier.ts
- src/theme/components/listitem.modifier.ts
- src/theme/components/menu.modifier.ts
- src/theme/components/menuitem.modifier.ts
- src/theme/components/tab.modifier.ts
- src/theme/components/tabs.modifier.ts
This PR partially fixes [#12739](https://github.com/meshery/meshery/issues/12739) Consistent Qanelas Soft font family
> chore: added fontfamily for base component

- src/custom/Workspaces/WorkspaceCard.tsx
- src/custom/Workspaces/hooks/useDesignAssignment.tsx
- src/custom/Workspaces/hooks/useEnvironmentAssignment.tsx
- src/custom/Workspaces/hooks/useTeamAssignment.tsx
- src/custom/Workspaces/hooks/useViewsAssignment.tsx
> Add permission for the workspace cards

- src/theme/components/appbar.modifiter.ts
- src/theme/components/buttongroup.modifier.ts
- src/theme/components/link.modifier.ts
- src/theme/components/listitem.modifier.ts
- src/theme/components/menu.modifier.ts
- src/theme/components/menuitem.modifier.ts
- src/theme/components/tab.modifier.ts
- src/theme/components/tabs.modifier.ts
Reverts layer5io/sistent#907
@Vidit-Kushwaha
> Revert "chore: added fontfamily for base component"

- src/custom/DashboardWidgets/GettingStartedWidget/ActionButtonCard.tsx
- src/custom/DashboardWidgets/GettingStartedWidget/GetStartedModal.tsx
- src/custom/ShareModal/ShareModal.tsx
> fix: Corrected progress percentage calculation in the Getting Started card

- src/base/NoSsr/NoSsr.tsx
- src/base/NoSsr/index.ts
- src/base/index.tsx
> feat: add nossr component to sistent

- src/custom/ResourceDetailFormatters/Formatter.tsx
> feat: add some null checking in the container formatter

- src/custom/DashboardWidgets/GettingStartedWidget/ActionButtonCard.tsx
- src/custom/DashboardWidgets/PlainCard.tsx
- src/custom/DashboardWidgets/RecentDesignWidget.tsx
- src/custom/DashboardWidgets/WorkspaceActivityWidget.tsx
> feat: remove min-width from the dashboard widgets

- src/custom/CatalogDetail/OverviewSection.tsx
- src/custom/CatalogDetail/SocialSharePopper.tsx
- src/custom/CatalogDetail/UserInfo.tsx
- src/custom/VisibilityChipMenu/VisibilityChipMenu.tsx
> feat: change the position of visiblity button

- src/custom/CustomTooltip/customTooltip.tsx
Signed-off-by: mrmerlin320 <mrmerlin320@gmail.com>
> fix: update custom tooltip styles

- src/custom/ResourceDetailFormatters/styles.ts
- src/custom/ResponsiveDataTable.tsx
- src/custom/Workspaces/styles.tsx
> fix: workspace card formatting issue

- package-lock.json
- package.json
- tsup.config.ts
>  remove mui libraries from the peer dependencies

- src/custom/ResponsiveDataTable.tsx
> Fix: Improved table sort arrow theme compatibility

- src/custom/ResponsiveDataTable.tsx
- src/custom/UsersTable/UsersTable.tsx
- src/theme/components.ts
- src/theme/components/table.modifier.ts
- src/theme/index.tsx
- Remove custom theme for the table.
- Use modifiers to change the table theme styling from the existing theme.
- Use QanelasSoft font family in textfield
- 
> feat: update theme for mui datatable

- package-lock.json
- package.json
> chore: bump xstate/react

- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/UsersTable/UserTableAvatarInfo.tsx
> fix: empty email field in the design table

- src/custom/CatalogDetail/ActionButton.tsx
- src/custom/DashboardWidgets/GettingStartedWidget/ActionButtonCard.tsx
- src/custom/Workspaces/styles.tsx
- src/theme/components/button.modifier.ts
- src/theme/theme.ts
> Revert "feat: add common border radius to all buttons"

- src/theme/palette.ts
> add primary color and update secondary text color from pallete

- src/custom/TeamTable/TeamTableConfiguration.tsx
> fix: e.undefined issue in teams table

- src/utils/time.utils.tsx
> fix: remove timezone from full formatted time function

- src/custom/DashboardWidgets/GettingStartedWidget/GetStartedModal.tsx
> fix: remove background image from CheckField component

- package-lock.json
- package.json
- src/custom/DashboardWidgets/WorkspaceActivityWidget.tsx
- src/custom/ResourceDetailFormatters/useResourceCleanData.ts
- src/schemas/createAndEditEnvironment/schema.tsx
- src/utils/time.utils.tsx
> fix: add 'name' as a required field in environment schema

- src/base/index.tsx
> fix: export AlertTitle component from base index

- src/custom/Workspaces/WorkspaceRecentActivityModal.tsx
> fix: update header icon in WorkspaceRecentActivityModal

- .husky/commit-msg
- src/custom/Workspaces/WorkspaceTeamsTable.tsx
> Manage Teams to Assign Teams

- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
> update move design icon

- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/Workspaces/DesignTable.tsx
- src/custom/Workspaces/WorkspaceViewsTable.tsx
> update workspace tables

- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
> fix build issues

- package-lock.json
- package.json
> Use @layer5/schemas schema package

- package-lock.json
- package.json
- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/Workspaces/DesignTable.tsx
- src/custom/Workspaces/WorkspaceViewsTable.tsx
- src/schemas/createAndEditWorkspace/schema.tsx
> add visibility change functionlity in workspae tables

- src/custom/Workspaces/DesignTable.tsx
- src/custom/Workspaces/WorkspaceViewsTable.tsx
> feat: update workspace table toolbar

- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/ResponsiveDataTable.tsx
- src/custom/TooltipIconButton/TooltipIconButton.tsx
- src/custom/Workspaces/DesignTable.tsx
- src/custom/Workspaces/WorkspaceViewsTable.tsx
> fix: pagination for workspace designs and views table

- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/Workspaces/WorkspaceViewsTable.tsx
> update action titles for design and view tables

- package-lock.json
- package.json
- src/constants/constants.ts
- src/custom/ShareModal/ShareModal.tsx
- src/custom/UserSearchField/UserSearchField.tsx
- src/utils/permissions.ts
- src/utils/routing.ts
cloud need to be updated before merge and release 
> Share modal

- src/custom/Modal/index.tsx
> fix: double scrollbar issue in modal

- src/custom/CatalogDesignTable/CatalogDesignTable.tsx
> remove duplicate date handle logic in catalog table

- src/custom/DashboardWidgets/GettingStartedWidget/JourneyModal.tsx
This pr fixes image stretching 
https://github.com/layer5io/meshery-cloud/issues/3429
> fix:image aspect ratio

- src/custom/VisibilityChipMenu/VisibilityChipMenu.tsx
> VisibilityChipMenu: Increase font size

- src/custom/CatalogFilterSection/CatalogFilterSidebar.tsx
> Fix: Padding for Filter Panel in Catalog

- src/custom/PerformersSection/PerformersSection.tsx
- src/custom/PerformersSection/styles.tsx
> Fix: Carousel For Performance Section

- src/constants/constants.ts
- src/custom/CatalogDesignTable/AuthorCell.tsx
- src/custom/CatalogDetail/ChallengesSection.tsx
- src/custom/CatalogDetail/LearningSection.tsx
- src/custom/CatalogDetail/UserInfo.tsx
- src/custom/UsersTable/UserTableAvatarInfo.tsx
- src/hooks/index.ts
- src/hooks/useRoomActivity.ts
- src/index.tsx
> Create useRoomActivity hook for get collaboration info

- src/custom/Carousel/style.tsx
- src/custom/PerformersSection/styles.tsx
> Fix: Performace carousal Width

- src/custom/NavigationNavbar/navigationNavbar.tsx
> Whats New Display Fix

- src/custom/CatalogFilterSection/CatalogFilterSidebar.tsx
- src/custom/CatalogFilterSection/FilterSection.tsx
- src/custom/CatalogFilterSection/style.tsx
> Fix: Meshery-Cloud Filter Drawer Title

- src/custom/UniversalFilter.tsx
> Fix: Mobile View for Filter

- src/custom/UniversalFilter.tsx
> Fix: Bug in Web View Connection Filter

- src/icons/Export/ExportIcon.tsx
- src/icons/Export/index.ts
- src/icons/index.ts
> feat: add export icon

- src/custom/ShareModal/ShareModal.tsx
- src/utils/permissions.ts
> add supoort for multi sharing in share modal

- src/icons/Open/OpenFileIcon.tsx
- src/icons/Open/index.tsx
> Fix: Add OpenFileIcon

- src/constants/constants.ts
- src/custom/CatalogDesignTable/DesignTableColumnConfig.tsx
- src/custom/Workspaces/WorkspaceContentMoveModal.tsx
- src/custom/Workspaces/index.ts
- src/icons/MoveFile/MoveFileIcon.tsx
- src/icons/MoveFile/index.ts
- src/icons/index.ts
> feat: add workspace content move modal

- src/theme/palette.ts
> add secondary color for light and dark mode

- src/custom/ShareModal/ShareModal.tsx
> fix: share modal link formatting issue

- package-lock.json
> update package name

- src/custom/CustomCatalog/CustomCard.tsx
- src/custom/CustomCatalog/style.tsx
This PR fixes https://github.com/layer5io/meshery-cloud/issues/3534
will dynamically adjust whether card has a ribbion or not.
> fix: Support level ribbon overlaps design title

- src/custom/UniversalFilter.tsx
> fix font color in filter div

- .github/workflows/bump-meshery-version.yml
- README.md
- src/custom/ErrorBoundary/README.md
- src/custom/readme.md
- src/schemas/readme.md
> Chore: rename package repo

- src/custom/Modal/index.tsx
This PR adds classname to modal header to make it easy to access.
> Fix: Adding Class to Modal Header and Footer

- site/gatsby-browser.js
This PR fixes # https://github.com/layer5io/layer5/issues/6544
> removed duplicate React import

- src/custom/SearchBar.tsx
fixes #1080
I didn't test this. I am making an assumption that this has the desired effect.
> [Button] Set line-height to 'auto' globally

- src/custom/NavigationNavbar/navigationNavbar.tsx
This PR adds playwright test ids to the nav component. This will allow us to improve coverage of the site navigation flows
> feat: added testids to nav component

- src/custom/LearningCard/LearningCard.tsx
> add learningCard color

- src/custom/LearningCard/LearningCard.tsx
- src/custom/LearningCard/style.tsx
> add modal for learningCard && fix learningCard design.

- src/custom/TeamTable/TeamTable.tsx
- src/custom/UsersTable/UsersTable.tsx
- src/custom/Workspaces/WorkspaceTeamsTable.tsx
After merging this merge : https://github.com/layer5io/meshery-cloud/pull/3779 🔴 
This PR fixes https://github.com/layer5io/meshery-cloud/issues/3768
> add:Ability to assign/unassign role to user from team table.

- src/custom/UserSearchField/UserSearchFieldInput.tsx
This PR fixes https://github.com/layer5io/meshery-cloud/issues/3516
This PR fixes https://github.com/layer5io/meshery-cloud/issues/3822
📹 :
https://github.com/user-attachments/assets/c9bfe03d-24c5-4016-bdaf-8237962d49d0
> user search is not properly working across cloud ui

- src/custom/Modal/index.tsx
- src/custom/ModalCard/ModalCard.tsx
- src/custom/Prompt/promt-component.tsx
- src/custom/SearchBar.tsx
- src/custom/Stepper/index.tsx
This PR adds test ids for the design page. 
> feat: added test ids for design page

- .husky/pre-commit
- package.json
- src/custom/CollaboratorAvatarGroup/CollaboratorAvatarGroup.tsx
style: enhance tooltip layout in CollaboratorAvatarGroup component
> refactor: update pre-commit hook to run npm test and adjust husky prepare script

- src/custom/CollaboratorAvatarGroup/CollaboratorAvatarGroup.tsx
> Update CollaboratorAvatarGroup.tsx: Move Divider down one element.

- src/icons/Info/InfoCircle.tsx
> keep modal helperIcon white

- src/custom/UniversalFilter.tsx
addes test ids to filter component 
> feat: added test ids to filter

- CONTRIBUTING.md
- src/custom/Modal/index.tsx
- src/theme/ThemeProvider.tsx
- src/theme/index.tsx
- src/theme/palette.ts
- src/theme/theme.ts
lint the using make lint to follow project 
This PR fixes # none 
> lint the  file

- src/custom/CustomCatalog/style.tsx
This PR fixes [#3857](https://github.com/layer5io/meshery-cloud/issues/3857)
> Add border for custom Catalog cards
