Makefile, README.md
This PR adds
- the packages we have now, `@layer5/sistent-components` and `@layer5/sistent-svg`
- Removes the template `Makefile` and update to use `yarn` commands
- Updates `README` on how to install `yarn` specific version and use `yarn` to install the dependencies
=> [docs] Update Makefile, and README.md

README.md, packages/rtk-query-codegen/README.md, packages/rtk-query-codegen/app.js, packages/rtk-query-codegen/empty-api.ts, packages/rtk-query-codegen/openapi-config.ts, packages/rtk-query-codegen/package-lock.json, packages/rtk-query-codegen/package.json, packages/rtk-query-codegen/tsconfig.json
created a cli for codegen of rtk-query apis from openapi schema
=> Added rtkquery codegen package

.github/workflows/lint.yml
This PR fixes the lint.yaml workflow, which has been failing. This PR eliminates the node12 error message seen while using older version of the Actions. The pre-existing issue with eslint not being available persists, though:
```
Run yarn lint && yarn format:check && yarn lint-staged
Oops! Something went wrong! :(
ESLint: 8.50.0
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/home/runner/work/sistent/sistent/apps/design-system".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
npm install @typescript-eslint/eslint-plugin@latest --save-dev
The plugin "@typescript-eslint/eslint-plugin" …
```
=> [CI] fix failing workflow: upgrade linter actions

packages/components/src/custom/TypingFilter/TypingFIlterInput.tsx, packages/components/src/custom/TypingFilter/TypingFIlters.tsx, packages/components/src/custom/TypingFilter/TypingFilterSuggestions.tsx, packages/components/src/custom/TypingFilter/index.tsx, packages/components/src/utils/typing.state.tsx, packages/components/src/utils/typing.utils.ts
=> feat(components): Create TypingFilter component

.github/ISSUE_TEMPLATE/question.md
The links to the Figma design file have been updated from the Layer5 link to the Sistent link
=> Figma design file link update

README.md, src/custom/Modal/index.tsx, src/custom/SearchBar.tsx, src/theme/components/button.modifier.ts, src/theme/palette.ts
1. Add new tokens
2. add danger button for modals
3. fix theme for modals
4. fix theme for search for `standard `variant
=> Enhancements in tokens and components

src/custom/CustomTooltip/customTooltip.tsx, src/custom/Markdown/index.tsx, src/custom/Markdown/style.tsx, src/custom/index.tsx
This PR adds a new mardown renderer, as the old one was causing issues with keeping the custom tooltips consistent with Figma designs. 
=> Feat: Separate Markdown Renderer for Tooltips

src/custom/Markdown/index.tsx, src/custom/Markdown/style.tsx
Signed-off-by: Sudhanshu Dasgupta <dasguptashivam23@gmail.com>
This PR fixes the onclick functionality with anchor tags inside tooltips which was not clickable
=> Fix onClick func for `a` tag for tooltips 

src/custom/CustomTooltip/customTooltip.tsx
- In meshery UI, ziCalc is used to give tooltips a zindex of ziCalc(5), so I instead migrated it here, thus eliminating the need for ziCalc in meshery and meshery cloud.
Moreover, in meshmap  many components are given a high zindex which results in the tooltip not displaying properly.
In meshmap, no ziCalc value exceeds ziCalc(9) and thus I have set this value to remedy the problem there too.
- The tooltip was also not rendering content which was not in string format making it hard to catch bugs and refactor.
So I updated the condition for title usage.
=> [Tooltip] Update zindex and title display condition

package.json
This PR fixes #633
- The module field has been replaced by correct file name.
- And now sistent supports CommonJS modules.
=> Fix: package.json module field

src/custom/Markdown/index.tsx
This PR fixes the click event on links inside tooltips which was mainly occurring inside modal . Moving `event propogation` below now ensures that the link is opened first, and then the event propagation is stopped.
Adding `as="a"` ensures that the StyledMarkdown component is rendered as an <a> tag, making it behave correctly as a hyperlink.
https://github.com/layer5io/sistent/assets/90546692/f0de8ad2-2fae-4315-8ba6-273757f74913
=> Fix click event for tooltip

src/custom/Feedback/FeedbackButton.tsx, src/custom/Feedback/style.tsx, src/custom/Modal/index.tsx, src/custom/ModalCard/style.tsx
This PR fixes the standard style for feedback component which is standard style for modal
=> Fix feedback component to use standard style

src/custom/CustomTooltip/customTooltip.tsx, src/custom/CustomTooltip/index.tsx, src/custom/CustomTooltip/infoTooltip.tsx, src/custom/index.tsx
This PR adds InfoTooltip, which was previously in cloud
- I have added the component under the CustomTooltip folder.
- This might need to be changed to tooltip, but the folder name is hardcoded in many other custom-components in Sistent.
=> feat: Migrate infoTooltip from cloud

package-lock.json, package.json, src/custom/Markdown/index.tsx
This PR fixes the issue to not render html ssupported tags inside markddown component.
By default the react markdown package does not allow to render html tags due to security reason so we need to use a plugin that is [rehype](https://www.npmjs.com/package/react-markdown#appendix-a-html-in-markdown)
For context we can read here: https://www.npmjs.com/package/react-markdown#appendix-a-html-in-markdown
=> Html tag support in markdown component

src/custom/ActionButton/ActionButton.tsx
This PR enriches ActionButton by
- adding show field for skip showing options
- adding Divider option to show divider in dropdown
- defaultActionDisabled to disable the default button when not allowed
=> ench: ActionButton for new designs

src/theme/components.ts, src/theme/components/buttongroup.modifier.ts
This PR fixes ButtonGroup component
- 
=> feat: add default Theme for MuiButtonGroup component

src/custom/SetupPrerequisite/style.tsx
This PR updates the SetupPreReq Card component's CSS to have `flex: 1` property.
=> [chore] Update setup prerequisite card css

src/custom/Markdown/index.tsx, src/custom/Markdown/style.tsx
1. Pre tag of html under markdown component to fix its overflowing
2. add background theme 
example:
=> Fix `pre` tag of html and its theme

src/theme/colors/colors.ts
=> feat(603): Added red-orange color palette

src/custom/CustomTooltip/customTooltip.tsx, src/custom/ResponsiveDataTable.tsx
- Add Customtooltip as default for data tables
- remove the click effect for tooltip to show content 
- inject sistent theme into tables to support it.
=> Add `customtooltip` as default for tables and fix around it

src/custom/TransferModal/TransferList/TransferList.tsx
This PR fixes the bug which was arising when we are trying to unassign items and it does not update immediately.
https://github.com/user-attachments/assets/51b6c404-2fb2-47e4-8073-4deb3d468768
=> [bug fix bug in unassign items in transferList component

src/custom/ResponsiveDataTable.tsx
1. support to pass any custom component in action
2. close action menu when clicked on any action
=> Add  option for `custom` action in action component

src/custom/StyledChapter/StyledChapter.tsx
=> chore: using brand colors

.github/workflows/release.yml
=> Remove `npm install` from build job

src/custom/Modal/index.tsx
This div prevents the footer from utilizing its full width. If we set `width: 100%`, it still not resolves the issue. I checked all the modal footers, and there are no side effects from this change.
Before: 
After
=> Remove unnecessary div wrapper in Modal component

package.json
=> Remove duplicate dependencies @types/lodash

src/custom/CatalogFilterSection/CatalogFilterSidebar.tsx, src/custom/CatalogFilterSection/CatalogFilterSidebarState.tsx, src/custom/CatalogFilterSection/FilterSection.tsx, src/custom/CatalogFilterSection/index.tsx, src/custom/CatalogFilterSection/style.tsx, src/custom/index.tsx
=> Convert cloud catalog filter section to sistent

src/custom/CatalogFilterSection/CatalogFilterSidebar.tsx, src/custom/CatalogFilterSection/FilterSection.tsx, src/custom/CatalogFilterSection/style.tsx, src/custom/CustomCatalog/custom-card.tsx
=> Enhancement on new created sistent component

src/custom/LearningCard/LearningCard.tsx
In NextJS 14 have no longer supporting passing `<a>` tag element directly, but need to encapsulate by using `next/link` like [this](https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag), because the a tag is to deep inside the element, we need to make it optional and pass from the outside of sistent
=> refactor: make the link tag optional on learning card

src/custom/StyledSearchBar/StyledSearchBar.tsx
This pull request includes several changes to the `StyledSearchBar` component in `src/custom/StyledSearchBar/StyledSearchBar.tsx` to improve its functionality and usability. The most important changes include replacing `useCallback` with `useEffect` for handling debounced input changes, adding a `debounceTime` prop, and ensuring the input value is synchronized with the `value` prop.
* Replaced `useCallback` with `useEffect` to handle debounced input changes, ensuring the debounce logic is more efficient and easier to manage. (`src/custom/StyledSearchBar/StyledSearchBar.tsx`, [src/custom/StyledSearchBar/StyledSearchBar.tsxL3-R3](diffhunk://#diff-e1662285ab295a30b37880c22f262c4005e0c8ac5ae39f341adfa89b875d3983L3-R3))
* Added a new `debounceTime` prop to `SearchBarProps` to allow …
=> Fix debouncing cleanup issue in styled search bar

src/icons/Menu/MenuIcon.tsx
This PR fixes an issue where the AddIcon code was mistakenly used for the MenuIcon. Now, the correct MenuIcon code is in place, resolving the visual discrepancy.
The issue number is #769 
=> Changed the Add icon code that was present in MenuIcon.tsx with MenuIcon

src/custom/NavigationNavbar/navigationNavbar.tsx, src/custom/NavigationNavbar/style.tsx
=> Make navigation navbar more generic to use for the use in meshery ui

src/icons/Workspace/WorkspaceIcon.tsx
This PR fixes the ability to use secondaryFill in the `workspaceIcon` and customize the `opacity`.
=> Enhance WorkspaceIcon with Opacity and Fill Color Support

src/custom/CatalogDetail/ActionButton.tsx, src/custom/CatalogDetail/LeftPanel.tsx, src/custom/CustomTooltip/customTooltip.tsx
=> add 'Open in Playground' action button conditionally

src/custom/Prompt/promt-component.tsx
=> add headericon for prompt

src/custom/CustomTooltip/customTooltip.tsx
This PR fixes #793
Before
After
=> Updated custom-tooltip style

src/constants/iconsSizes.ts, src/custom/UserSearchField/UserSearchField.tsx, src/custom/VisibilityChipMenu/VisibilityChipMenu.tsx
=> make visibility chip smaller and fix build failed issue

src/custom/CatalogDetail/ActionButton.tsx, src/custom/CatalogDetail/LeftPanel.tsx, src/custom/CatalogDetail/SocialSharePopper.tsx, src/custom/ShareModal/ShareModal.tsx
=> feat(catalog): restructure share action and add delete action

src/custom/CatalogDetail/OverviewSection.tsx, src/custom/CatalogDetail/RightPanel.tsx, src/custom/CatalogDetail/SocialSharePopper.tsx
=> feat(visibilitySelector): add visibility selector to change catalog visibility

package-lock.json, package.json, src/custom/BBChart/BBChart.tsx, src/custom/BBChart/index.ts, src/custom/ResourceDetailFormatters/Component.tsx, src/custom/ResourceDetailFormatters/Details.tsx, src/custom/ResourceDetailFormatters/ExpandArrow.tsx, src/custom/ResourceDetailFormatters/Formatter.tsx, src/custom/ResourceDetailFormatters/context.tsx, src/custom/ResourceDetailFormatters/index.ts, src/custom/ResourceDetailFormatters/styles.ts, src/custom/ResourceDetailFormatters/types.ts, src/custom/ResourceDetailFormatters/useResourceCleanData.ts, src/custom/ResourceDetailFormatters/utils.ts, src/custom/index.tsx
=> Create custom formatters and the resource data extract hooks for the resource detail view

src/theme/typography.ts
This PR fixes the buttons variant to follow qanelas soft font family. To achieve this we can directly fix the typography variant that is passed to button component,
=> use qanelas soft for buttons

src/custom/Markdown/index.tsx, src/custom/Markdown/style.tsx, src/index.tsx, src/theme/palette.ts, src/utils/components.ts, src/utils/index.ts
=> Code styling

src/theme/palette.ts
=> change disable color for the button

src/custom/TransferModal/TransferList/TransferList.tsx
Add `GithubIcon` to TransferList
=> Fix: add GithubIcon to TransferList

src/schemas/importDesign/schema.tsx, src/schemas/importModel/schema.tsx, src/schemas/importModel/uiSchema.tsx, src/schemas/index.tsx
1. More descriptive information messages for model and design import modals.
2. Added schema for model import modal here in sistent. 
**Prev behaviour:** This schema was present in meshkit schemas and fetched via server (api/schema/resource/{resourcename})
**Current behaviour:** Schema fetched from sistent. 
**Why?** To keep it consistent with Filter and Design. Meshkit Schemas are deprecated.
- [*] Yes, I signed my commits.
=> fix: improve info messages for model and design import modals

package-lock.json, package.json
This pull request includes a change to the `package.json` file to expand the compatibility range for the `react` and `react-dom` peer dependencies.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L83-R84): Updated `react` and `react-dom` peer dependencies to support both version `^17.0.2` and `^18.3.1` for better compatibility with the extensions.
=> feat: add support for both react version

src/custom/Carousel/Carousel.tsx, src/custom/Carousel/index.tsx, src/custom/Carousel/style.tsx, src/custom/CatalogDetail/RelatedDesigns.tsx, src/custom/CatalogDetail/style.tsx, src/custom/index.tsx
This PR refactors the Carousel component to make it available for external usage. Previously, it was used internally, but now it is exposed for broader accessibility.
=> refactor: expose Carousel component for external usage

src/custom/ShareModal/ShareModal.tsx
=> Sharing Modal: Add link to docs

README.md
=> Add Instructions for how to refer to your local Sistent fork

src/custom/Modal/index.tsx
=> Feat: FullScreen Mode in Modal

src/custom/Modal/index.tsx
This PR fixes https://github.com/layer5io/meshery-cloud/issues/3602
=> fix doublescrollbar occuring when datatables are placed inside modal

src/custom/CustomCatalog/Helper.ts
This PR fixes: https://github.com/layer5io/meshery-cloud/issues/3585
There are three relevant states for a design: **private**, **public**, and **published**. The `private` and `public` states should both reflect the current draft's version number, which is stored in the `version` field. Only a `published` design should display the `published_version`.
The bug was that the UI was incorrectly displaying the `published_version` for designs that were set to `public`. This created problems:
1.  **Inconsistent Versions**: If a public design had no `published_version`, the UI would show an incorrect fallback value (like `0.0.0` or `""`).
2.  **Wrong Versions**: If a public design has a `published_version`, the UI would show an incorrect value. …
=> fix: Unify version display for public and private designs

src/custom/CollaboratorAvatarGroup/CollaboratorAvatarGroup.tsx
=> add: collaboration panel button in avatar tooltip

src/base/Tooltip/Tooltip.tsx, src/base/Tooltip/index.tsx, src/custom/HelperTextPopover/helperTextPopover.tsx, src/custom/HelperTextPopover/index.ts, src/custom/Modal/index.tsx, src/custom/UniversalFilter.tsx, src/custom/index.ts
This PR replaces muiTooltip component in helperText component with muiPopOver, as the popover is better in terms of usablitiy and links can be clicked and text can be copied easily without the problem of disappering as incase of muiTooltip.
Incase of muiPopover , we have to click on the [i] button rather than hovering over it.
https://github.com/user-attachments/assets/029b56e8-cf8a-4045-9342-cb3e6bd0eff7
=> Replacement of MuiTooltip with MuiPopover in helperText Component

src/custom/CustomTooltip/customTooltip.tsx
https://github.com/user-attachments/assets/44ff71d1-a003-4044-9b67-9e4127ab5070
**Changes:**
1. Tooltip leave duration: Initially would disappear immediately -> now will be there for 0.7sec
2. milliseconds to wait before showing the tooltip when one was already recently opened -> 0.4sec
3. Tooltip appear on hover : Initial 0.1sec -> now 0.15sec
=> fix: custom - tooltip on hover should stay there for atleast some seconds

src/icons/CatalogIcon/CatalogIcon.tsx
This was discovered through a console error message in the Meshery UI.
=> chore: Remove unused field `tertiaryFill` from type definition.

src/icons/Academy/AcademyIcon.tsx, src/icons/Academy/index.ts, src/icons/index.ts
This PR adds the Academy icon to the Sistent project’s icon collection.
- Please review the Academy icon’s design
- The icon can be customized by changing the colors of the top, center, and bottom sections.
-  topFill
-  centerFill
-  bottomFill
- Example : <AcademyIcon **topFill**={theme?.palette?.background?.inverse || "#eee"}/>;
**Default Icon :**
=> feat(icons): add Academy icon

src/icons/index.ts
**Hacktoberfest Contribution 🎉**
This PR fixes #1170 
This PR adds MesheryIcon to the Sistent icon collection. The current library does not include Meshery’s official icon, and adding it ensures consistency with Meshery branding and provides developers with easy access when using Sistent.
- Added MesheryIcon to the Sistent icon set.
=> Added Meshery Icon in Icon collections 

src/custom/StyledTextField/index.tsx, src/custom/index.tsx
This PR fixes #1175
Currently we use FormControl, InputLabel and Select for input fields or select dropdowns, but we face the issue for the label not getting the space allocated dynamically. I did test the components in Staclblitz from the official MUI website, and did not find any solution to it.
This new component: Replaces FormControl + TextField combinations with a single, properly styled component that fixes label/border intersection issues.
Features:
1. Dynamic Label Positioning
2. Consistent Brand Styling
3. Improved Developer Experience - The component can be changed as per needs by passing props to it
4. All other TextField props supported
Working: 
https://github.com/user-attachments/assets/46251d5d-65f2-4bfb-b19a-d83f3080e776 …
=> Add new component to fix the dynamic allocation for label space
